version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ADP'
      MYSQL_USER: 'adp'
      MYSQL_PASSWORD: 'adp'
      MYSQL_ROOT_PASSWORD: 'dev'
    ports:
      - '3306:3306'
  #######################################
  # php app
  #######################################
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - db
    ports:
      - "80:80"
    volumes:
      - ./public_html:/var/www/html
      - ./docker/httpd/sites:/etc/apache2/sites-enabled
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  client:
    container_name: box-client
    image: iavega/box-client:latest
    depends_on:
      - backend
    volumes:
      - './client:/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
